<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HazardsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hazards = [
            ['name' => 'Blocked fire exits'],
            ['name' => 'Faulty fire alarms'],
            ['name' => 'Overloaded electrical circuits'],
            ['name' => 'Flammable liquid storage'],
            ['name' => 'Inadequate fire extinguishers'],
            ['name' => 'Improper handling of combustible materials'],
            ['name' => 'Lack of emergency lighting'],
            ['name' => 'Poorly maintained sprinkler systems'],
            ['name' => 'Smoking in prohibited areas'],
            ['name' => 'Faulty electrical equipment'],
            ['name' => 'Improper disposal of oily rags'],
            ['name' => 'Obstructed fire hydrants'],
            ['name' => 'Damaged fire doors'],
            ['name' => 'Insufficient fire safety training'],
            ['name' => 'Improper storage of gas cylinders'],
            ['name' => 'Lack of fire evacuation plans'],
            ['name' => 'Blocked sprinkler heads'],
            ['name' => 'Accumulation of combustible dust'],
            ['name' => 'Inadequate ventilation in hazardous areas'],
            ['name' => 'Faulty emergency power systems'],
            ['name' => 'Improperly stored chemicals'],
            ['name' => 'Lack of fire-resistant barriers'],
            ['name' => 'Overheating equipment'],
            ['name' => 'Improper use of extension cords'],
            ['name' => 'Lack of fire drills'],
            ['name' => 'Inadequate firefighting water supply'],
            ['name' => 'Faulty smoke detectors'],
            ['name' => 'Improper disposal of hazardous waste'],
            ['name' => 'Blocked access to fire control panels'],
            ['name' => 'Lack of proper signage for emergency exits'],
            ['name' => 'Inadequate personal protective equipment (PPE)'],
            ['name' => 'Exposed electrical wiring'],
            ['name' => 'Improper storage of pressurized containers'],
            ['name' => 'Lack of fire-resistant clothing for workers'],
            ['name' => 'Inadequate emergency response procedures'],
            ['name' => 'Faulty emergency shutdown systems'],
            ['name' => 'Improper handling of hot work (welding, cutting, etc.)'],
            ['name' => 'Lack of proper labeling for hazardous materials'],
            ['name' => 'Inadequate spacing between stored materials'],
            ['name' => 'Faulty or missing fire dampers in HVAC systems'],
            ['name' => 'Improper storage of oxidizers'],
            ['name' => 'Lack of proper grounding for static electricity'],
            ['name' => 'Inadequate containment for spills'],
            ['name' => 'Faulty gas detection systems'],
            ['name' => 'Improper use of space heaters'],
            ['name' => 'Lack of proper fire-rated construction materials'],
            ['name' => 'Inadequate maintenance of fire pumps'],
            ['name' => 'Faulty emergency communication systems'],
            ['name' => 'Improper storage of batteries'],
            ['name' => 'Lack of proper safety data sheets (SDS)'],
            ['name' => 'Inadequate lighting in emergency exit routes'],
            ['name' => 'Faulty pressure relief valves'],
            ['name' => 'Improper handling of compressed gases'],
            ['name' => 'Lack of proper fall protection'],
            ['name' => 'Inadequate machine guarding'],
            ['name' => 'Faulty lockout/tagout procedures'],
            ['name' => 'Improper storage of radioactive materials'],
            ['name' => 'Lack of proper confined space entry procedures'],
            ['name' => 'Inadequate eye wash stations and safety showers'],
            ['name' => 'Faulty dust collection systems'],
            ['name' => 'Improper handling of asbestos-containing materials'],
            ['name' => 'Lack of proper respiratory protection'],
            ['name' => 'Inadequate noise control measures'],
            ['name' => 'Faulty automatic fire suppression systems'],
            ['name' => 'Improper storage of corrosive substances'],
            ['name' => 'Lack of proper ergonomic equipment'],
            ['name' => 'Inadequate first aid supplies and facilities'],
            ['name' => 'Faulty emergency eyewash stations'],
            ['name' => 'Improper handling of biological hazards'],
            ['name' => 'Lack of proper safety interlocks on equipment'],
            ['name' => 'Inadequate lightning protection'],
            ['name' => 'Faulty pressure vessels'],
            ['name' => 'Improper storage of explosive materials'],
            ['name' => 'Lack of proper safety guards on machinery'],
            ['name' => 'Inadequate waste management procedures'],
            ['name' => 'Faulty boiler systems'],
            ['name' => 'Improper handling of cryogenic liquids'],
            ['name' => 'Lack of proper safety barriers'],
            ['name' => 'Inadequate control of ignition sources'],
            ['name' => 'Faulty temperature control systems'],
            ['name' => 'Improper storage of reactive substances'],
            ['name' => 'Lack of proper safety warning systems'],
            ['name' => 'Inadequate emergency escape breathing devices'],
            ['name' => 'Faulty fume hoods'],
            ['name' => 'Improper handling of nanomaterials'],
            ['name' => 'Lack of proper safety training for new employees'],
            ['name' => 'Inadequate electrical grounding'],
            ['name' => 'Faulty fuel storage tanks'],
            ['name' => 'Improper storage of pyrophoric materials'],
            ['name' => 'Lack of proper safety audits and inspections'],
            ['name' => 'Inadequate flood prevention measures'],
            ['name' => 'Faulty fire suppression system controls'],
            ['name' => 'Improper handling of laser equipment'],
            ['name' => 'Lack of proper safety committees'],
            ['name' => 'Inadequate earthquake preparedness'],
            ['name' => 'Faulty emergency generators'],
            ['name' => 'Improper storage of water-reactive substances'],
            ['name' => 'Lack of proper safety incentive programs'],
            ['name' => 'Inadequate security measures for hazardous areas'],
            ['name' => 'Faulty fire-resistant coatings on structural elements'],
        ];

        DB::table('hazards')->insert($hazards);
    }
}
