<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SuggestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suggestions = [
            ['name' => 'Inspect fire extinguishers for visible damage, corrosion, or tampering.'],
            ['name' => 'Check fire extinguisher pressure gauges to ensure they are in the operable range.'],
            ['name' => 'Verify that fire extinguisher safety seals and tamper indicators are intact.'],
            ['name' => 'Ensure fire extinguishers are in their designated locations and easily accessible.'],
            ['name' => 'Check the weight of fire extinguishers to verify fullness.'],
            ['name' => 'Inspect fire hoses for cuts, abrasions, or signs of damage.'],
            ['name' => 'Verify that fire hose couplings are tight and free from corrosion.'],
            ['name' => 'Conduct flow tests on fire hoses to ensure proper water pressure and volume.'],
            ['name' => 'Check that fire hose nozzles are functioning correctly and free from obstructions.'],
            ['name' => 'Ensure fire hose cabinets or reels are easily accessible and in good condition.'],
            ['name' => 'Test manual fire alarm pull stations.'],
            ['name' => 'Inspect and test smoke detectors and heat detectors.'],
            ['name' => 'Check audio and visual alarm indicators for proper function.'],
            ['name' => 'Verify central station monitoring connection for the fire alarm system.'],
            ['name' => 'Inspect sprinkler system control valves and gauges.'],
            ['name' => 'Look for signs of leakage or corrosion in the sprinkler system.'],
            ['name' => 'Ensure sprinkler heads are unobstructed and have adequate clearance.'],
            ['name' => 'Test emergency lighting systems and exit signs.'],
            ['name' => 'Inspect fire doors to ensure they close and latch properly.'],
            ['name' => 'Check for any obstructions to fire door closure.'],
            ['name' => 'Verify that fire-rating labels on doors and barriers are intact and legible.'],
            ['name' => 'Review and update facility evacuation plans.'],
            ['name' => 'Conduct fire drills and evacuation exercises.'],
            ['name' => 'Inspect fire hydrants for damage, leaks, or obstructions.'],
            ['name' => 'Check the condition and supply of emergency kits.'],
            ['name' => 'Verify that flammable material storage areas are properly maintained.'],
            ['name' => 'Inspect electrical systems for overloaded circuits or damaged wiring.'],
            ['name' => 'Clean or replace HVAC air filters.'],
            ['name' => 'Check fire dampers in HVAC systems for proper operation.'],
            ['name' => 'Inspect and test carbon monoxide detectors.'],
            ['name' => 'Verify the availability and condition of personal protective equipment (PPE).'],
            ['name' => 'Ensure eye wash stations and safety showers are operational.'],
            ['name' => 'Check first aid kits and AED devices for completeness and function.'],
            ['name' => 'Conduct fire safety training for new employees.'],
            ['name' => 'Provide refresher training on fire prevention and response.'],
            ['name' => 'Update safety data sheets (SDS) for hazardous materials.'],
            ['name' => 'Maintain records of all fire safety inspections and tests.'],
            ['name' => 'Review and update emergency contact information.'],
            ['name' => 'Ensure proper documentation of all fire incidents and false alarms.'],
            ['name' => 'Verify that safety signage is in good condition and properly placed.'],
            ['name' => 'Inspect and maintain fire extinguisher mounting brackets.'],
            ['name' => 'Check that operating instructions on fire extinguishers are legible and facing outward.'],
            ['name' => 'Verify that fire extinguisher locations are properly marked.'],
            ['name' => 'Conduct annual professional inspection of fire extinguishers.'],
            ['name' => 'Perform hydrostatic testing of fire extinguishers as required.'],
            ['name' => 'Recharge or replace fire extinguishers after use or as necessary.'],
            ['name' => 'Inspect fire hose storage devices for proper functioning.'],
            ['name' => 'Ensure fire hoses are properly rolled or folded for quick deployment.'],
            ['name' => 'Conduct annual service testing of fire hoses.'],
            ['name' => 'Replace washers and gaskets on fire hose couplings as needed.'],
            ['name' => 'Verify that fire hose nozzles are set to the correct spray pattern.'],
            ['name' => 'Check the operation of fire hose valves and handles.'],
            ['name' => 'Ensure proper drainage for fire hose testing and maintenance areas.'],
            ['name' => 'Verify that fire hose length and diameter are appropriate for the facility.'],
            ['name' => 'Inspect fire department connections and ensure they are unobstructed.'],
            ['name' => 'Check that caps on fire department connections are in place and not damaged.'],
            ['name' => 'Verify that fire pump systems are operational and properly maintained.'],
            ['name' => 'Inspect and test backflow preventers in the fire suppression water supply.'],
            ['name' => 'Ensure that fire extinguisher and fire hose training is up to date for all relevant personnel.'],
            ['name' => 'Verify that maintenance logs for fire extinguishers and hoses are current and complete.'],
            ['name' => 'Visually inspect for damage, corrosion, or tampering.'],
            ['name' => 'Check pressure gauges are in the operable range.'],
            ['name' => 'Ensure safety seals and tamper indicators are intact.'],
            ['name' => 'Verify correct and visible placement.'],
            ['name' => 'Check for any obstructions to access.'],
            ['name' => 'Inspect for fullness by weighing or hefting.'],
            ['name' => 'Ensure operating instructions are legible and facing outward.'],
            ['name' => 'Check for any signs of use or discharge.'],
            ['name' => 'Test manual pull stations.'],
            ['name' => 'Inspect and test smoke detectors.'],
            ['name' => 'Check heat detectors for proper function.'],
            ['name' => 'Test audio and visual alarm indicators.'],
            ['name' => 'Verify central station monitoring connection.'],
            ['name' => 'Clean detector heads to prevent false alarms.'],
            ['name' => 'Test backup batteries.'],
            ['name' => 'Verify all zones are operational.'],
            ['name' => 'Check control panel for any trouble indicators.'],
            ['name' => 'Inspect control valves for proper position.'],
            ['name' => 'Check water pressure gauges.'],
            ['name' => 'Look for signs of leakage or corrosion.'],
            ['name' => 'Ensure sprinkler heads are unobstructed.'],
            ['name' => 'Verify adequate clearance below sprinkler heads.'],
            ['name' => 'Test water flow alarm devices.'],
            ['name' => 'Conduct main drain tests.'],
            ['name' => 'Check antifreeze solution in dry systems.'],
            ['name' => 'Inspect fire department connections.'],
            ['name' => 'Test functionality of emergency lights.'],
            ['name' => 'Check battery backup systems.'],
            ['name' => 'Ensure exit signs are illuminated and visible.'],
            ['name' => 'Verify correct placement of exit signs.'],
            ['name' => 'Clean fixtures and replace bulbs as needed.'],
            ['name' => 'Test photoluminescent exit path markings.'],
            ['name' => 'Inspect for proper closing and latching.'],
            ['name' => 'Check for damaged or missing door seals.'],
            ['name' => 'Ensure no obstructions to door closure.'],
            ['name' => 'Test hold-open devices and automatic closers.'],
            ['name' => 'Verify fire-rating labels are intact and legible.'],
            ['name' => 'Check for any holes or penetrations in fire barriers.'],
            ['name' => 'Review and update evacuation plans.'],
            ['name' => 'Ensure evacuation maps are current and posted.'],
            ['name' => 'Time evacuation procedures and identify bottlenecks.'],
            ['name' => 'Check condition and supply of emergency kits.'],
            ['name' => 'Verify assembly point locations are still suitable.'],
            ['name' => 'Inspect hydrants for damage or leaks.'],
            ['name' => 'Ensure hydrants are accessible and visible.'],
            ['name' => 'Check for adequate water pressure.'],
            ['name' => 'Verify hydrant caps are in place and operational.'],
            ['name' => 'Conduct flow tests as required.'],
            ['name' => 'Inspect fire pump and test its operation.'],
            ['name' => 'Check integrity of storage cabinets and containers.'],
            ['name' => 'Ensure proper labeling of all containers.'],
            ['name' => 'Verify ventilation systems are operational.'],
            ['name' => 'Check for any spills or leaks.'],
            ['name' => 'Ensure incompatible materials are properly separated.'],
            ['name' => 'Verify fire suppression systems in storage areas.'],
            ['name' => 'Inspect for overloaded circuits or outlets.'],
            ['name' => 'Check for frayed or damaged wiring.'],
            ['name' => 'Ensure proper use of extension cords (temporary only).'],
            ['name' => 'Verify GFCI outlets are functioning correctly.'],
            ['name' => 'Inspect electrical panels for signs of overheating.'],
            ['name' => 'Test emergency power systems and generators.'],
            ['name' => 'Clean or replace air filters.'],
            ['name' => 'Inspect ductwork for accumulation of dust or debris.'],
            ['name' => 'Check fire dampers for proper operation.'],
            ['name' => 'Ensure outdoor air intakes are clear of obstructions.'],
            ['name' => 'Verify proper function of smoke control systems.'],
            ['name' => 'Inspect belt drives and motors for wear.'],
            ['name' => 'Inspect condition of firefighting gear.'],
            ['name' => 'Check expiration dates on respirator cartridges.'],
            ['name' => 'Verify availability and condition of emergency escape respirators.'],
            ['name' => 'Check first aid kits and AED devices for completeness and function.'],
            ['name' => 'Conduct fire safety training for new employees.'],
            ['name' => 'Provide refresher training on fire prevention and response.'],
            ['name' => 'Update safety data sheets (SDS) for hazardous materials.'],
            ['name' => 'Maintain records of all inspections and tests.'],
            ['name' => 'Review and update emergency contact information.'],
            ['name' => 'Ensure proper documentation of all fire incidents and false alarms.'],
            ['name' => 'Inspect and test carbon monoxide detectors.'],
            ['name' => 'Check condition of lightning protection systems.'],
            ['name' => 'Verify functionality of security systems.'],
            ['name' => 'Inspect fall protection equipment.'],
            ['name' => 'Ensure proper storage and handling of compressed gas cylinders.'],
            ['name' => 'Check condition and placement of safety signage.'],
            ['name' => 'Test and maintain kitchen suppression systems.'],
            ['name' => 'Inspect and test clean agent suppression systems.'],
            ['name' => 'Verify operation of smoke control systems in atriums or large spaces.'],
            ['name' => 'Check specialized fire suppression systems for server rooms or data centers.'],
            ['name' => 'Inspect and test foam systems for flammable liquid hazards.'],
        ];

        DB::table('suggestions')->insert($suggestions);
    }
}
